import json
import time
import uuid
from pathlib import Path

from app.schemas.interface_inventory import InterfaceExportRecord, InterfaceInventoryResponse, InterfaceKtrSection, InterfaceRecord
from app.schemas.log import LogLevel
from app.services.log_service import JsonlLogService
from app.services.storage_paths import project_root


class InterfaceInventoryService:
    def __init__(self, logger: JsonlLogService) -> None:
        self.logger = logger
        self.root = project_root() / "exports" / "interfaces"
        self.root.mkdir(parents=True, exist_ok=True)
        self.last_event: tuple[str, dict] | None = None

    def inventory(self) -> InterfaceInventoryResponse:
        records = [self._localized(record) for record in self._records()]
        categories: dict[str, int] = {}
        for record in records:
            categories[record.category] = categories.get(record.category, 0) + 1
        return InterfaceInventoryResponse(interfaces=records, categories=categories)

    def ktr_section(self) -> InterfaceKtrSection:
        markdown = self._ktr_markdown([self._localized(record) for record in self._records()])
        plain_text = markdown.replace("#", "").replace("|", " ")
        return InterfaceKtrSection(markdown=markdown, plain_text=plain_text)

    def export(self) -> InterfaceExportRecord:
        export_id = f"interfaces-{time.strftime('%Y%m%d-%H%M%S')}-{uuid.uuid4().hex[:6]}"
        output_dir = self.root / export_id
        output_dir.mkdir(parents=True, exist_ok=True)
        inventory = self.inventory()
        ktr = self.ktr_section()
        json_path = output_dir / "interface_inventory.json"
        md_path = output_dir / "interface_inventory.md"
        ktr_path = output_dir / "ktr_4_3_interfaces.md"
        json_path.write_text(json.dumps(inventory.model_dump(mode="json"), indent=2), encoding="utf-8")
        md_path.write_text(self.markdown_inventory(), encoding="utf-8")
        ktr_path.write_text(ktr.markdown, encoding="utf-8")
        record = InterfaceExportRecord(
            export_id=export_id,
            output_dir=str(output_dir),
            files=[str(json_path), str(md_path), str(ktr_path)],
        )
        self._event("interfaces.export_completed", record.model_dump(mode="json"), "Interface inventory exported")
        return record

    def markdown_inventory(self) -> str:
        header = (
            "| Arayüz | Kategori | Üreten | Tüketen | Taşıma | Protokol | Mesaj formatı | Yön | "
            "Endpoint/Port | Güncelleme hızı | Güvenlik sınırı | Arıza davranışı | Doğrulama yöntemi | Doğrulama durumu | Readiness bağımlılığı | Operatöre görünür | Kanıt |\n"
            "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"
        )
        rows = []
        for item in [self._localized(record) for record in self._records()]:
            name = f"{item.display_name} ({item.name})" if item.display_name and item.display_name != item.name else item.name
            rows.append(
                f"| {name} | {item.category_label or item.category.replace('_', ' ').title()} | {item.producer} | {item.consumer} | "
                f"{item.transport} | {item.protocol} | {item.message_format} | {item.direction} | "
                f"{item.endpoint_or_port} | {item.update_rate} | {item.safety_boundary} | "
                f"{item.failure_behavior} | {item.verification_method} | {item.verification_status} | "
                f"{', '.join(item.readiness_profile_dependency) or 'all'} | {item.operator_visible} | {item.export_evidence_path or 'generated export'} |"
            )
        return "# Interface Inventory\n\n" + header + "\n" + "\n".join(rows) + "\n"

    def _event(self, event_type: str, payload: dict, message: str) -> None:
        self.last_event = (event_type, payload)
        self.logger.emit(LogLevel.INFO, "INTERFACES", message, payload)

    def _localized(self, item: InterfaceRecord) -> InterfaceRecord:
        category_labels = {
            "user_interface": "Kullanıcı Arayüzü",
            "rest_api": "REST API Arayüzü",
            "websocket": "WebSocket Olay Arayüzü",
            "mjpeg_stream": "MJPEG Görüntü Akışı",
            "camera_interface": "Cihaz Keşif ve Kamera Arayüzü",
            "vision_model_interface": "Görüntü İşleme Model Arayüzü",
            "pico_serial_telemetry": "Pico Seri Telemetri Arayüzü",
            "serial_protocol": "Seri Protokol Arayüzü",
            "safety_interface": "Güvenlik Arayüzü",
            "config_interface": "Konfigürasyon Arayüzü",
            "logging_interface": "Loglama Arayüzü",
            "dataset_replay_interface": "Veri Seti ve Replay Arayüzü",
            "report_export_interface": "Rapor Dışa Aktarım Arayüzü",
            "deployment_interface": "Dağıtım/Çalıştırma Arayüzü",
            "electronic_power_signal_interface_placeholder": "Elektronik Güç/Sinyal Arayüz Tanımı",
        }
        display_names = {
            "ui_vue_console": "Operatör Konsol Kullanıcı Arayüzü",
            "vision_adapter": "Görüntü İşleme Model Arayüzü",
            "vision_model_package_handoff": "Görüntü İşleme Model Paketi Arayüzü",
            "dataset_replay": "Veri Seti ve Replay Arayüzü",
            "safety_decision": "Güvenlik ve Karar Arayüzü",
            "report_export": "Rapor Dışa Aktarım Arayüzü",
            "portable_launcher": "Taşınabilir Başlatıcı Arayüzü",
            "electronic_signal_placeholder": "Elektronik Güç/Sinyal Arayüz Tanımı",
        }
        return item.model_copy(update={
            "display_name": display_names.get(item.interface_id, item.name),
            "category_label": category_labels.get(item.category, item.category.replace("_", " ").title()),
        })

    def _ktr_markdown(self, records: list[InterfaceRecord]) -> str:
        def tr(text: str) -> str:
            replacements = {
                "UI never authorizes physical fire or motion; backend remains authority.": "UI fiziksel atış veya hareket yetkisi vermez; yetkili güvenlik kararı backend tarafında kalır.",
                "Backend disconnected state is shown and no frontend mock fallback is used.": "Backend bağlantısı kesildiğinde operatöre açık durum gösterilir; frontend tarafında sahte bağlantı üretimi yapılmaz.",
                "Safety-changing calls are validated server-side and reject by default.": "Safety durumunu etkileyen çağrılar sunucu tarafında doğrulanır ve varsayılan olarak reddedilir.",
                "Controlled HTTP error with user-facing detail.": "Hata durumunda operatöre anlaşılır açıklama ve teknik detay içeren kontrollü HTTP yanıtı döner.",
                "Events are telemetry only and cannot trigger physical output.": "WebSocket olayları yalnızca telemetri amaçlıdır; fiziksel çıkış tetikleyemez.",
                "Frontend shows disconnected state and reconnects.": "Frontend bağlantı kesildi durumunu gösterir ve yeniden bağlanmayı dener.",
                "Frames are advisory and not connected to actuation.": "Görüntü kareleri yalnızca bilgilendirme amaçlıdır; aktuasyon yoluna bağlı değildir.",
                "Mock frame or unavailable warning without backend crash.": "Kamera yoksa backend çökmez; mock frame veya erişilemez uyarısı gösterilir.",
                "Camera settings cannot enable hardware commands.": "Kamera ayarları hardware command yolunu etkinleştiremez.",
                "Atomic apply rolls back to previous profile on failure.": "Ayar uygulama atomiktir; hata halinde önceki çalışan profile geri dönülür.",
                "Inference output is advisory and cannot generate physical command.": "Inference çıktısı tavsiye/metadata amaçlıdır; fiziksel komut üretemez.",
                "Missing model returns warning and keeps service alive.": "Model eksikse servis çökmez; kontrollü uyarı üretir.",
                "Read-only serial path; PC does not send actuation commands.": "Seri hat salt-okunur çalışır; PC aktuasyon komutu göndermez.",
                "No telemetry becomes warning, not crash.": "Telemetri yokluğu çökme değil uyarı durumudur.",
                "Real read-only mode blocks risky TX and physical commands.": "Gerçek read-only mod riskli TX ve fiziksel komutları engeller.",
                "Invalid frames produce controlled error events.": "Geçersiz paketler kontrollü hata olayına çevrilir.",
                "Reject-by-default policy remains backend-owned.": "Varsayılan reddetme politikası backend tarafından korunur.",
                "Critical safety invariant failure marks self-test failed.": "Kritik safety invariant bozulursa self-test başarısız işaretlenir.",
                "Unsafe hardware flags are rejected during validation.": "Güvensiz hardware bayrakları config doğrulamasında reddedilir.",
                "Backend startup fails controlled on unsafe config.": "Güvensiz config ile backend kontrollü şekilde başlatılmaz.",
                "Logging is passive and cannot execute commands.": "Loglama pasiftir; komut çalıştıramaz.",
                "Writable check reports warning/fail in first-run/self-test.": "Yazılabilirlik problemi first-run/self-test raporunda warning/fail olarak görünür.",
                "Dataset/replay output remains advisory and non-physical.": "Dataset/replay çıktısı tavsiye amaçlıdır ve fiziksel değildir.",
                "Validation reports missing files/bboxes before export.": "Export öncesi eksik dosya ve bbox problemleri validasyon raporunda gösterilir.",
                "Readiness does not authorize physical fire or motion.": "Readiness sonucu fiziksel atış veya hareket yetkisi vermez.",
                "Report export cannot arm or enable hardware.": "Rapor export işlemi sistemi arm edemez ve hardware enable yapamaz.",
                "Export failure is logged and shown to user.": "Export hatası loglanır ve kullanıcıya gösterilir.",
                "Launcher starts software only; it does not enable physical hardware.": "Launcher yalnızca yazılımı başlatır; fiziksel donanımı etkinleştirmez.",
                "Missing dependencies or busy port produce user-readable error.": "Eksik bağımlılık veya dolu port operatöre anlaşılır hata olarak gösterilir.",
                "No GPIO, STEP/DIR/PWM output is produced in this software phase.": "Bu yazılım fazında GPIO, STEP/DIR veya PWM çıkışı üretilmez.",
                "Physical command flags are rejected by config and runtime gates.": "Fiziksel komut bayrakları config ve runtime gate kontrolleri tarafından reddedilir.",
            }
            return replacements.get(text, text)

        def section(title: str, categories: set[str]) -> str:
            items = [item for item in records if item.category in categories]
            lines = [f"## {title}", ""]
            for item in items:
                lines.append(f"- **{item.display_name or item.name}:** {item.ktr_description}")
                lines.append(f"  Güvenlik sınırı: {tr(item.safety_boundary)}")
                lines.append(f"  Arıza davranışı: {tr(item.failure_behavior)}")
            return "\n".join(lines)

        sections = [
            "# KTR 4.3 Arayüzler",
            "",
            "Bu bölüm, İSTİKLAL C2 Console yazılımının operatör, backend servisleri, kamera/model katmanı, Pico seri telemetri hattı, veri kayıt sistemi ve rapor üretim bileşenleri arasındaki arayüzleri tanımlar. Tüm arayüzlerde varsayılan güvenlik politikası DISARMED, NO_FIRE, dry-run ve fiziksel komut kapalı durumudur.",
            "",
            section("Kullanıcı Arayüzü", {"user_interface"}),
            section("Yazılımsal Arayüzler", {"rest_api", "websocket", "config_interface", "logging_interface"}),
            section("Görüntü ve Model Arayüzleri", {"mjpeg_stream", "vision_model_interface"}),
            "## Görüntü İşleme Model Paketi Arayüzü",
            "",
            "Görüntü işleme ekibi modeli `models/incoming/<paket_adı>/` klasör yapısı veya güvenli ZIP import akışı ile teslim eder. Paket; model dosyasını, `metadata.json`, `classes.json` veya `classes.yaml`, `thresholds.json`, README ve opsiyonel örnek giriş/çıkışları içerir. Backend model package servisi dosya varlığını, checksum bilgisini, sınıf eşlemesini, threshold değerlerini ve advisory-only safety notunu doğrular.",
            "",
            "Test adaptörü geliştirme ve arayüz doğrulama amaçlıdır; yarışma modeli değildir. Production model paketi ise görüntü işleme ekibinden alınan gerçek modeldir, metadata/classes/thresholds dosyaları ile sisteme tanıtılır ve kod değişmeden import edilir.",
            "",
            "Test adaptörü veya fixture model paketi, yalnızca arayüz ve veri akışı doğrulaması için kullanılır; yarışma tespit modeli olarak değerlendirilmez.",
            "",
            "Frontend `/models` ekranı ile model paketi import edilir, paket şeması doğrulanır, aktif modele alınır, runtime önerileri incelenir ve dry-run test/benchmark sonucu görüntülenir. Vision runtime arayüzü `conf`, `iou`, `imgsz`, `max_det`, `device` ve tracker ayarlarını yönetir. Bu ayarlar yalnızca görüntü işleme parametrelerini değiştirir; safety state, fire policy ve hardware state değişmez.",
            "",
            "Görüntü işleme modeli, komuta kontrol yazılımına yalnızca sınıf, güven skoru, konum ve zaman bilgisi içeren algılama metadatası sağlar; bu metadata tek başına fiziksel atış veya hareket komutu üretmez.",
            "",
            "OpenCV Live Circle Surrogate, gerçek laptop/USB kamera veya mock kamera üzerinden canlı frame alma, overlay, snapshot, FPS/latency ve loglama akışını sınamak için kullanılır. Mock kamera çalıştırmasında kaynak `mock_camera_circle_surrogate`, frame origin `mock_frame`; gerçek kamera çalıştırmasında kaynak `live_camera_circle_surrogate`, frame origin `real_capture` olarak raporlanır. OpenCV yuvarlak algılayıcı yalnızca arayüz/görüntü aktarımı/overlay/loglama testi içindir; production YOLO veya yarışma modeli değildir. Mock frame çıktısı gerçek kamera doğrulaması olarak değerlendirilmez.",
            "",
            "## Legacy Perception and Real Camera Evidence Interface",
            "",
            "Bu arayüz, eski stable tracker sisteminden çıkarılan kamera profili, HSV renk eşiği, OpenCV detector parametreleri, target selection ve smoothing/Kalman metadata bilgisini yeni C2 Console içinde advisory/evidence-only olarak sunar. `/api/vision/legacy-presets`, `/api/vision/legacy-presets/{preset_id}`, `/api/vision/real-camera/status`, `/api/vision/real-camera/capture-evidence` ve `/api/vision/real-camera/latest` endpointleri yalnızca perception presetleri ve gerçek kamera evidence metadata üretir.",
            "",
            "Real camera evidence yalnızca görüntü işleme kanıtı ve metadata üretir. Bu arayüz motor, servo, GPIO, PWM, STEP/DIR, fire veya physical serial command üretmez; tüm çıktılar `advisory_only=true`, `physical_command_enabled=false` ve `no_physical_command_generated=true` alanlarını taşır.",
            "",
            "## Camera Host Discovery and Real Camera Acceptance Boundary",
            "",
            "`/api/vision/camera-host/status`, `/api/vision/camera-host/diagnose`, `/api/vision/camera-host/latest` ve `/api/vision/real-camera/acceptance` endpointleri Linux host seviyesinde `/dev/video*`, `v4l2-ctl`, `ffmpeg`, USB/PCI kamera bilgisi, kullanıcı grup/permission çıktısı, OpenCV frame capture sonucu ve kernel camera/v4l2 mesajlarını read-only diagnostic olarak toplar. Ubuntu kamera uygulaması laptop kamerasını görmüyorsa bu durum application-level real camera acceptance olarak geçmez; `blocked_by_host_os`, `partial` veya `passed` evidence olarak açıkça sınıflandırılır.",
            "",
            "Kamera host tarafından görünmüyorsa competition readiness için blocker olarak değerlendirilir. Mock/surrogate evidence release demo için kullanılabilir ancak real camera evidence yerine geçmez. Bu arayüz fiziksel komut üretmez; motor, servo, fire, GPIO, PWM, STEP/DIR, TMC write, serial TX/write veya hardware enable yolu eklemez. Tüm çıktılar `advisory_only=true`, `physical_command_enabled=false` ve `no_physical_command_generated=true` alanlarını taşır.",
            "",
            "Internal laptop camera and external USB camera are represented as separate camera sources. External USB camera evidence is accepted only when the backend captures a real frame from the USB camera device path, e.g. `/dev/video2`. Browser-level camera success alone is treated as operator observation, not backend acceptance.",
            "",
            "USB kamera kanıtı, backend tarafından `/dev/video2` üzerinden gerçek frame alınarak üretilir. Bu kanıt yalnızca görüntü alma ve evidence üretimi içindir; motor, servo, GPIO, PWM, STEP/DIR, serial TX veya fire komutu üretmez.",
            "",
            "## Motion Direction Semantics and Calibration Interface",
            "",
            "Bu arayüz, görüntü koordinatları, hedef hata yönü, kamera pan/tilt yönü ve motor yön mapping semantiğini operatör gözlemiyle kalibre etmek için kullanılır. `/api/calibration/direction/status`, `/api/calibration/direction/simulate`, `/api/calibration/direction/record-observation`, `/api/calibration/direction/save-profile`, `/api/calibration/direction/reset` ve `/api/calibration/direction/latest` endpointleri yalnızca direction simulation, advisory mapping ve calibration evidence metadata üretir.",
            "",
            "Bu fazda fiziksel motor hareketi, GPIO/PWM/STEP/DIR çıkışı, serial write veya hardware enable yoktur. Üretilen çıktı yalnızca advisory direction profile ve evidence metadata’dır; tüm çıktılar `advisory_only=true`, `physical_command_enabled=false` ve `no_physical_command_generated=true` alanlarını taşır.",
            "",
            "Release candidate profili test adaptörü veya açık model durumu ile çalışabilir. Competition rehearsal profili için üretim YOLO modeli, eksiksiz class mapping ve başarılı model test sonucu gerekir.",
            "",
            section("Cihaz Keşif ve Kamera Arayüzleri", {"camera_interface"}),
            section("Pico Seri Telemetri Arayüzü", {"pico_serial_telemetry", "serial_protocol"}),
            "## Pico Read-Only Hardware Discovery Interface",
            "",
            "Bu arayüz, Pico/Arduino seri port keşfi, host permission diagnosis ve RX-only telemetry kanıtı için kullanılır. `/api/pico/discovery/ports`, `/api/pico/read-only/permission-status`, `/api/pico/read-only/connect`, `/api/pico/read-only/disconnect`, `/api/pico/read-only/status`, `/api/pico/read-only/latest-telemetry`, `/api/pico/read-only/capture-evidence` ve `/api/pico/read-only/latest-evidence` endpointleri port metadata, dialout/permission blocker, bağlantı sağlığı, heartbeat/firmware/telemetry snapshot ve evidence export bilgisi sağlar.",
            "",
            "Bu fazda serial write, command TX, motor jog, STEP/DIR/PWM/GPIO, TMC current write, hardware enable veya fire/trigger yolu yoktur. Cihazdan yalnızca kendiliğinden gelen telemetry okunur ve evidence olarak kaydedilir. Permission düzeltmeleri yalnızca operatöre manuel öneri olarak sunulur; sistem otomatik sudo/usermod/chmod çalıştırmaz. Tüm çıktılar `serial_write_enabled=false`, `command_tx_enabled=false`, `physical_command_enabled=false` ve `no_physical_command_generated=true` alanlarını taşır.",
            "",
            section("Güvenlik Arayüzleri", {"safety_interface"}),
            section("Veri, Log ve Rapor Arayüzleri", {"dataset_replay_interface", "logging_interface", "report_export_interface"}),
            "## Veri Seti, Oturum Kaydı ve Replay Arayüzü",
            "",
            "Data Lab arayüzü, vision mock/surrogate detection çıktılarından oturum seviyesinde kanıt üretir. `/api/data-lab/status`, `/api/data-lab/sessions`, `/api/data-lab/sessions/latest`, `/api/data-lab/sessions/record-latest`, `/api/data-lab/replay/status`, `/api/data-lab/replay/run`, `/api/data-lab/annotations/candidates`, `/api/data-lab/annotations/review`, `/api/data-lab/dataset-health`, `/api/data-lab/detection-events-sample` ve `/api/data-lab/export` endpointleri session metadata, replay sonucu, annotation candidate review, dataset health ve detection event sample JSONL bilgisini sağlar.",
            "",
            "Bu arayüzün dosya çıktıları `session.json`, `detections.jsonl`, `annotations.jsonl`, `data_lab_summary.md`, `data_lab_sessions.json`, `detection_events_sample.jsonl`, `replay_readiness.md`, `replay_summary.md`, `replay_latest.json`, `annotation_candidates.json`, `annotation_review_summary.md` ve `dataset_health_summary.md` dosyalarıdır. Tüm çıktılar `advisory_only=true` ve `no_physical_command_generated=true` güvenlik kanıtını taşır.",
            "",
            "Veri seti, oturum kaydı ve replay arayüzü yalnızca operatör inceleme, KTR kanıtı, dataset hazırlığı ve replay hazırlığı içindir; fiziksel komut, GPIO, motor, servo, fire, STEP/DIR/PWM veya hardware enable yolu üretmez.",
            "",
            "## Demo Evidence Timeline Arayüzü",
            "",
            "Demo Evidence Timeline arayüzü, dashboard safety state, first-run/profile state, vision mock/surrogate metadata, Data Lab session/replay/annotation/dataset health, report export ve log kanıtlarını tek bir sıralı demo akışında birleştirir. `/api/demo/timeline`, `/api/demo/run`, `/api/demo/latest` ve `/api/demo/readiness` endpointleri operatöre demo kanıtlarının durumunu ve final verdict bilgisini sağlar.",
            "",
            "Jury Demo Center, aynı kanıtları tek bakışta sunar: sistem güvenliği, release demo verdict, competition blockers, dataset readiness, latest Data Lab session, latest replay, annotation review, evidence index ve latest KTR/report export. `jury_demo_summary.md`, `release_demo_verdict.json`, `evidence_index.md`, `known_limitations.md` ve `demo_operator_script.md` dosyaları jüri/demo paketinin parçasıdır.",
            "",
            "Bu arayüz fiziksel komut üretmez; yalnızca demo, evidence, replay ve rapor amaçlı metadata üretir. Yarışma hazır kararı için production YOLO modeli, gerçek kamera kanıtı, Pico telemetry verification ve self-test gerekir. Mock/surrogate evidence yalnızca demo/release kanıtıdır.",
            "",
            section("Dağıtım/Çalıştırma Arayüzü", {"deployment_interface"}),
            "## Taşınabilir Çalıştırma ve Kurulum Arayüzü",
            "",
            "Windows `.bat` ve Linux `.sh` başlatıcıları backend FastAPI servis katmanını ve hazır frontend static arayüzünü yerel makinede açar. İlk çalıştırma kontrolleri Python/uv bağımlılıklarını, frontend static build varlığını, yazılabilir log/export klasörlerini, cihaz keşfini, kamera kaynak bağlamasını ve model runtime bağlamasını raporlar.",
            "",
            "First Run ve release preflight kontrolleri eksik Pico veya production YOLO modelini release/demo profili için uyarı olarak, competition rehearsal profili için engelleyici durum olarak gösterir. Başlatıcı arayüzleri yalnızca yazılımı çalıştırır; fiziksel komut yetkisi vermez.",
            "",
            "Release candidate profili, sistemin donanımsız ve üretim YOLO modeli olmadan güvenli şekilde açılabildiğini doğrular. Competition rehearsal profili ise üretim YOLO modeli, doğrulanmış Pico telemetrisi, gerçek kamera/probe doğrulaması ve çalıştırılmış self-test gerektirir; bu koşullar eksikse prova hazırlığı engellenmiş sayılır.",
            "",
            section("Elektronik Güç/Sinyal Arayüz Tanımı", {"electronic_power_signal_interface_placeholder"}),
            "",
            "OpenCV daire algılayıcı yalnızca test adaptörüdür; üretim YOLO modeli veya yarışma dedektörü olarak sunulmaz. Üretim modeli görüntü işleme ekibi tarafından sağlanacak model dosyası ve adapter sözleşmesi üzerinden yüklenir.",
            "",
            "Bu yazılım fazında fiziksel çıkış üretilmemekte; ancak sistem arayüz tanımı kapsamında Pico, TMC2209, servo, E-stop ve limit girişleri için planlanan güç/sinyal arayüzleri envantere alınmıştır.",
            "",
            "Bu envanter rapor üretimi içindir; fiziksel komut üretmez, safety state değiştirmez ve hardware enable yetkisi vermez.",
        ]
        return "\n\n".join(sections)

    def _records(self) -> list[InterfaceRecord]:
        return [
            InterfaceRecord(
                interface_id="ui_vue_console",
                name="Operator Console UI",
                category="user_interface",
                direction="operator to system and system to operator",
                producer="Vue 3 frontend",
                consumer="Operator",
                transport="Browser UI",
                protocol="HTML/CSS/TypeScript",
                message_format="Pinia state and rendered views",
                endpoint_or_port="/, /safety, /vision, /devices, /reports",
                update_rate="interactive",
                data_fields=["system mode", "safety gates", "device inventory", "vision settings", "reports"],
                safety_boundary="UI never authorizes physical fire or motion; backend remains authority.",
                failure_behavior="Backend disconnected state is shown and no frontend mock fallback is used.",
                verification_method="Frontend build, route smoke tests, screenshots",
                ktr_description="Operatörün dashboard, safety, cihaz yönetimi, vision, data lab ve rapor ekranlarını tek konsoldan izlediği kullanıcı arayüzüdür.",
            ),
            InterfaceRecord(
                interface_id="rest_api",
                name="Frontend ↔ Backend REST",
                category="rest_api",
                direction="bidirectional request/response",
                producer="Vue API clients",
                consumer="FastAPI routers",
                transport="HTTP",
                protocol="REST JSON",
                message_format="Pydantic validated JSON",
                endpoint_or_port="/api/*",
                update_rate="operator action and polling",
                data_fields=["state", "commands", "config", "reports", "devices"],
                safety_boundary="Safety-changing calls are validated server-side and reject by default.",
                failure_behavior="Controlled HTTP error with user-facing detail.",
                verification_method="Pytest endpoint coverage",
                ktr_description="Komuta kontrol arayüzünün backend servisleriyle ana JSON haberleşme katmanı.",
            ),
            InterfaceRecord(
                interface_id="websocket_events",
                name="Backend to Frontend WebSocket Events",
                category="websocket",
                direction="backend to frontend",
                producer="FastAPI runtime services",
                consumer="Vue/Pinia stores",
                transport="WebSocket",
                protocol="JSON event envelope",
                message_format="type, ts, seq, payload, summary",
                endpoint_or_port="/ws",
                update_rate="runtime event driven",
                data_fields=["safety", "pico", "serial", "vision", "motion", "self_test", "reports"],
                safety_boundary="Events are telemetry only and cannot trigger physical output.",
                failure_behavior="Frontend shows disconnected state and reconnects.",
                verification_method="WebSocket smoke tests",
                ktr_description="Canlı telemetri ve olay akışı için tek yönlü backend-yetkili event kanalı.",
            ),
            InterfaceRecord(
                interface_id="camera_mjpeg",
                name="Camera to UI MJPEG Stream",
                category="mjpeg_stream",
                direction="backend to browser",
                producer="CameraService",
                consumer="Vision view",
                transport="HTTP multipart stream",
                protocol="MJPEG",
                message_format="JPEG frames",
                endpoint_or_port="/api/camera/stream.mjpg",
                update_rate="configured FPS",
                data_fields=["frame image"],
                safety_boundary="Frames are advisory and not connected to actuation.",
                failure_behavior="Mock frame or unavailable warning without backend crash.",
                verification_method="Camera status and vision route smoke tests",
                ktr_description="Kamera görüntüsünün arayüze güvenli, salt-görsel aktarımı.",
            ),
            InterfaceRecord(
                interface_id="camera_runtime",
                name="Camera Source Runtime Interface",
                category="camera_interface",
                direction="operator to backend and backend to camera",
                producer="Camera runtime manager",
                consumer="OpenCV/video device",
                transport="OpenCV VideoCapture",
                protocol="V4L/OpenCV properties",
                message_format="runtime profile JSON",
                endpoint_or_port="/api/camera/runtime/*",
                update_rate="on apply/probe",
                data_fields=["device path", "width", "height", "fps", "format", "roi"],
                safety_boundary="Camera settings cannot enable hardware commands.",
                failure_behavior="Atomic apply rolls back to previous profile on failure.",
                verification_method="Camera runtime tests and UI smoke",
                ktr_description="Laptop/USB/mock kamera seçimi ve çözünürlük/FPS/format yönetimi.",
            ),
            InterfaceRecord(
                interface_id="vision_adapter",
                name="Vision Model Adapter Interface",
                category="vision_model_interface",
                direction="backend to model and model to backend",
                producer="Vision team model or test adapter",
                consumer="InferenceAdapterService",
                transport="Python adapter",
                protocol="adapter contract",
                message_format="detections, latency, warnings",
                endpoint_or_port="/api/vision/runtime/*, /api/models/*",
                update_rate="frame/replay/test inference",
                data_fields=["bbox", "confidence", "class", "latency", "model_id"],
                safety_boundary="Inference output is advisory and cannot generate physical command.",
                failure_behavior="Missing model returns warning and keeps service alive.",
                verification_method="Model registry and adapter tests",
                ktr_description="Görüntü işleme ekibinin vereceği YOLO/ONNX modelini arayüze bağlayan adapter sözleşmesidir. OpenCV daire algılayıcı yalnızca test adaptörüdür; üretim vision algoritması veya yarışma dedektörü olarak sunulmaz.",
            ),
            InterfaceRecord(
                interface_id="vision_model_package_handoff",
                name="Vision Model Package Handoff Interface",
                category="vision_model_interface",
                direction="vision team package to backend registry and frontend operator review",
                producer="Vision team model package",
                consumer="ModelPackageService, VisionRuntimeSettingsService, Models UI",
                transport="Filesystem or safe ZIP import",
                protocol="metadata.json, classes.json/yaml, thresholds.json, model file checksum",
                message_format="model_id, version, class_id_to_name, thresholds, runtime recommendations",
                endpoint_or_port="/api/models/packages/*",
                update_rate="on import/validate/activate/test",
                data_fields=["model_file", "checksum", "expected_classes", "class_mapping", "conf", "iou", "imgsz"],
                safety_boundary="Model package import and testing are advisory only and cannot generate physical command.",
                failure_behavior="Missing metadata, missing class mapping or missing model file blocks activation and competition readiness.",
                verification_method="Package validation endpoint, dry-run model test, KTR export evidence",
                ktr_description="Görüntü işleme ekibinin model dosyasını ve metadata sözleşmesini kod değişmeden sisteme aldığı, doğruladığı ve active model durumuna bağladığı arayüzdür.",
                verification_status="implemented",
                readiness_profile_dependency=["release_candidate_ready", "competition_rehearsal_ready"],
                operator_visible=True,
                export_evidence_path="ktr_4_3_interfaces.md, model_package_inventory.json",
            ),
            InterfaceRecord(
                interface_id="legacy_perception_real_camera_evidence",
                name="Legacy Perception and Real Camera Evidence Interface",
                category="vision_model_interface",
                direction="legacy audit outputs to backend evidence and frontend operator review",
                producer="LegacyPerceptionService",
                consumer="Vision UI, Data Lab, Reports/KTR export",
                transport="Filesystem audit JSON + REST",
                protocol="Pydantic JSON contract",
                message_format="legacy perception presets, real camera evidence metadata",
                endpoint_or_port="/api/vision/legacy-presets, /api/vision/real-camera/*",
                update_rate="on operator refresh/capture/export",
                data_fields=["camera profile", "HSV thresholds", "detector parameters", "target center metadata", "safety evidence"],
                safety_boundary="Inference output is advisory and cannot generate physical command.",
                failure_behavior="Real camera absence returns controlled not_available evidence without mock fallback.",
                verification_method="Endpoint tests, Data Lab export, KTR export evidence",
                ktr_description="Eski stable tracker audit bilgisinden güvenli perception presetleri ve gerçek kamera evidence metadata üreten arayüzdür; motor/servo/fire/GPIO/PWM/STEP/DIR veya physical serial command yolu üretmez.",
                verification_status="implemented",
                readiness_profile_dependency=["release_candidate_ready"],
                operator_visible=True,
                export_evidence_path="legacy_perception_presets.json, real_camera_evidence_latest.json",
            ),
            InterfaceRecord(
                interface_id="motion_direction_semantics_calibration",
                name="Motion Direction Semantics and Calibration Interface",
                category="safety_interface",
                direction="operator observation to advisory calibration profile",
                producer="CalibrationService",
                consumer="Calibration UI, Data Lab, Reports/KTR export",
                transport="REST JSON + filesystem evidence",
                protocol="Pydantic direction calibration contract",
                message_format="target_error, required_camera_motion, expected_image_response, axis multipliers",
                endpoint_or_port="/api/calibration/direction/*",
                update_rate="on simulate/observation/save",
                data_fields=["target_error_x", "target_error_y", "x_axis_multiplier", "y_axis_multiplier", "axis_swap"],
                safety_boundary="Inference output is advisory and cannot generate physical command.",
                failure_behavior="Invalid or unknown observation remains advisory and requires retest.",
                verification_method="Endpoint tests, Data Lab export, KTR export evidence",
                ktr_description="Görüntü yön semantiği ile ilerideki motor yön mapping bilgisini fiziksel hareket üretmeden simüle eden ve operatör gözlemiyle advisory calibration profile oluşturan arayüzdür.",
                verification_status="implemented",
                readiness_profile_dependency=["release_candidate_ready"],
                operator_visible=True,
                export_evidence_path="direction_calibration_profile.json, motion_semantics_contract.md",
            ),
            InterfaceRecord(
                interface_id="pico_readonly_telemetry",
                name="Backend ↔ Pico Serial JSON-line",
                category="pico_serial_telemetry",
                direction="Pico to backend",
                producer="Telemetry-only Pico firmware",
                consumer="HardwareDiscoveryService",
                transport="USB serial",
                protocol="JSON-line telemetry",
                message_format="device, firmware_version, estop_state, safe_state, limits",
                endpoint_or_port="/dev/ttyACM* or COM*",
                update_rate="2-5 Hz expected",
                data_fields=["firmware", "estop", "driver_enabled", "pan/tilt steps", "safe_state"],
                safety_boundary="Read-only serial path; PC does not send actuation commands.",
                failure_behavior="No telemetry becomes warning, not crash.",
                verification_method="Read-only acceptance tests",
                ktr_description="Pico 2 cihazının yalnızca durum telemetrisi yayınladığı güvenli keşif arayüzü.",
            ),
            InterfaceRecord(
                interface_id="pico_readonly_hardware_discovery",
                name="Pico Read-Only Hardware Discovery Interface",
                category="pico_serial_telemetry",
                direction="microcontroller to backend RX-only",
                producer="Pico/Arduino telemetry firmware or operating system serial metadata",
                consumer="PicoService, Pico UI, Data Lab, Reports/KTR export",
                transport="USB serial RX-only",
                protocol="JSON-line telemetry if device publishes it",
                message_format="port metadata, raw RX sample, firmware, heartbeat, estop, limits, warning/fault state",
                endpoint_or_port="/api/pico/discovery/ports, /api/pico/read-only/*",
                update_rate="on refresh/connect/status/evidence capture",
                data_fields=["port", "vid", "pid", "serial_number", "firmware_version", "heartbeat", "limits", "estop_state"],
                safety_boundary="Read-only serial path; PC does not send actuation commands.",
                failure_behavior="Disconnected or no telemetry returns controlled not_available evidence.",
                verification_method="Endpoint tests, log evidence, Data Lab export, KTR export",
                ktr_description="Pico/Arduino seri portlarını keşfeden ve yalnızca cihazın kendiliğinden yayınladığı telemetriyi evidence olarak okuyan RX-only arayüzdür.",
                verification_status="implemented",
                readiness_profile_dependency=["hardware_telemetry_ready"],
                operator_visible=True,
                export_evidence_path="pico_readonly_status.json, pico_readonly_port_inventory.json",
            ),
            InterfaceRecord(
                interface_id="serial_json_binary",
                name="Serial Protocol Codec",
                category="serial_protocol",
                direction="designed bidirectional, currently command-disabled for real hardware",
                producer="SerialService/protocol codecs",
                consumer="Mock transport or future Pico firmware",
                transport="Serial",
                protocol="JSON-line dev protocol and binary CRC16 codec",
                message_format="newline JSON or AA TYPE SEQ LEN PAYLOAD CRC END",
                endpoint_or_port="/api/serial/*",
                update_rate="command/event driven",
                data_fields=["seq", "ack", "nack", "telemetry", "crc"],
                safety_boundary="Real read-only mode blocks risky TX and physical commands.",
                failure_behavior="Invalid frames produce controlled error events.",
                verification_method="CRC/ACK/NACK tests",
                ktr_description="Geliştirme JSON-line protokolü ve testlenmiş binary paket codec altyapısı.",
            ),
            InterfaceRecord(
                interface_id="safety_decision",
                name="Safety and Decision Gate Interface",
                category="safety_interface",
                direction="backend internal and frontend display",
                producer="DecisionEngine/SafetyService",
                consumer="Safety UI, fire request evaluator, self-test",
                transport="Python service + REST/WebSocket",
                protocol="Pydantic state objects",
                message_format="gates, blocking reasons, decision state",
                endpoint_or_port="/api/safety/*, /api/decision/*",
                update_rate="on event/evaluation",
                data_fields=["NO_FIRE", "DISARMED", "dry_run", "gates", "reason"],
                safety_boundary="Reject-by-default policy remains backend-owned.",
                failure_behavior="Critical safety invariant failure marks self-test failed.",
                verification_method="Safety and self-test pytest coverage",
                ktr_description="NO_FIRE, dry-run, hedef sınıflandırma ve gate tabanlı güvenlik karar arayüzü.",
            ),
            InterfaceRecord(
                interface_id="yaml_config",
                name="YAML Configuration Interface",
                category="config_interface",
                direction="filesystem to backend",
                producer="config/config.yaml",
                consumer="ConfigService",
                transport="Filesystem",
                protocol="YAML + Pydantic validation",
                message_format="typed configuration sections",
                endpoint_or_port="config/config.yaml",
                update_rate="startup/runtime apply for selected profiles",
                data_fields=["system", "hardware", "serial", "camera", "vision", "reports"],
                safety_boundary="Unsafe hardware flags are rejected during validation.",
                failure_behavior="Backend startup fails controlled on unsafe config.",
                verification_method="Config validation tests",
                ktr_description="Sistem, cihaz, kamera, model ve rapor ayarlarının doğrulanan konfigürasyon katmanı.",
            ),
            InterfaceRecord(
                interface_id="jsonl_logging",
                name="JSONL Logging Interface",
                category="logging_interface",
                direction="backend/frontend events to filesystem",
                producer="Runtime services and Logs UI",
                consumer="logs and exports folders",
                transport="Filesystem",
                protocol="JSONL",
                message_format="one JSON object per line",
                endpoint_or_port="logs/, exports/logs/",
                update_rate="event driven",
                data_fields=["timestamp", "level", "source", "message", "payload"],
                safety_boundary="Logging is passive and cannot execute commands.",
                failure_behavior="Writable check reports warning/fail in first-run/self-test.",
                verification_method="JSONL export tests",
                ktr_description="Komut, safety, cihaz, rapor ve kullanıcı olaylarının kanıt amaçlı kayıt arayüzü.",
            ),
            InterfaceRecord(
                interface_id="dataset_replay",
                name="Dataset and Replay File Interface",
                category="dataset_replay_interface",
                direction="backend to filesystem and UI",
                producer="Session/Dataset/Replay services",
                consumer="Data Lab and YOLO export",
                transport="Filesystem + REST",
                protocol="JSON/JSONL/YOLO text",
                message_format="session.json, annotations.jsonl, data.yaml, label txt",
                endpoint_or_port="/api/sessions, /api/datasets, /api/replay",
                update_rate="operator action and replay timing",
                data_fields=["frames", "annotations", "detections", "metadata", "split"],
                safety_boundary="Dataset/replay output remains advisory and non-physical.",
                failure_behavior="Validation reports missing files/bboxes before export.",
                verification_method="Phase 9 E2E and dataset tests",
                ktr_description="Saha verisi, annotation, replay, YOLO export ve Data Lab session evidence dosya arayüzleri. Vision mock/surrogate detection çıktıları session-level metadata olarak kaydedilir ve fiziksel komut üretmez.",
            ),
            InterfaceRecord(
                interface_id="self_test_all_services",
                name="Self-test ↔ all services",
                category="safety_interface",
                direction="backend internal",
                producer="SelfTestService",
                consumer="Runtime services and operator UI",
                transport="Python service + REST/WebSocket",
                protocol="internal service checks",
                message_format="self-test steps and readiness summary",
                endpoint_or_port="/api/self-test/*",
                update_rate="operator action",
                data_fields=["step status", "readiness", "warnings", "critical failures"],
                safety_boundary="Readiness does not authorize physical fire or motion.",
                failure_behavior="Critical safety invariant failure marks run failed.",
                verification_method="Self-test pytest coverage and UI smoke",
                ktr_description="Tüm servisleri güvenli demo hazırlığı için kontrol eden kabul testi arayüzü.",
            ),
            InterfaceRecord(
                interface_id="report_export",
                name="Reports/KTR export ↔ backend services",
                category="report_export_interface",
                direction="backend to filesystem/frontend",
                producer="ReportExportService",
                consumer="Reports UI and KTR package",
                transport="REST + filesystem",
                protocol="Markdown/JSON",
                message_format="summary files and metadata",
                endpoint_or_port="/api/reports/*",
                update_rate="operator action",
                data_fields=["KTR summary", "safety summary", "inventory", "checklists"],
                safety_boundary="Report export cannot arm or enable hardware.",
                failure_behavior="Export failure is logged and shown to user.",
                verification_method="Report export quality gate tests",
                ktr_description="Jüri/KTR/demo paketlerinin üretildiği rapor arayüzü.",
            ),
            InterfaceRecord(
                interface_id="demo_evidence_timeline",
                name="Demo Evidence Timeline Interface",
                display_name="Demo Kanıt Zaman Çizelgesi Arayüzü",
                category="report_export_interface",
                direction="backend services to operator UI and report files",
                producer="DemoTimelineService",
                consumer="Demo UI, Dashboard, Reports/KTR export",
                transport="REST + filesystem",
                protocol="JSON/Markdown timeline",
                message_format="demo_timeline.json, demo_timeline.md, demo_readiness_summary.md, jury_demo_summary.md, evidence_index.md",
                endpoint_or_port="/api/demo/timeline, /api/demo/run, /api/demo/latest, /api/demo/readiness",
                update_rate="operator action",
                data_fields=["timeline steps", "evidence refs", "demo verdict", "safety invariant"],
                safety_boundary="Demo timeline cannot arm, enable hardware or issue physical commands.",
                failure_behavior="Missing evidence appears as warning/blocker in the timeline.",
                verification_method="Phase 21 API, report export and UI smoke tests",
                ktr_description="Dağınık demo kanıtlarını Jury Demo Center ve zaman çizelgesinde birleştiren arayüzdür; mock/surrogate kanıtları yalnızca demo/release kanıtı olarak gösterir.",
                export_evidence_path="demo_timeline.json, demo_timeline.md, demo_readiness_summary.md, jury_demo_summary.md, evidence_index.md, demo_operator_script.md",
            ),
            InterfaceRecord(
                interface_id="cleanroom_jury_rehearsal",
                name="Jury Rehearsal and Clean-room Release Verification Interface",
                display_name="Juri Provasi ve Clean-room Release Dogrulama Arayuzu",
                category="deployment_interface",
                direction="release ZIP and runtime evidence to operator UI and KTR reports",
                producer="ReleaseService and DemoTimelineService",
                consumer="Demo UI, Dashboard, Reports/KTR export",
                transport="REST + filesystem",
                protocol="JSON/Markdown evidence package",
                message_format="cleanroom_smoke_results.json, release_portability_audit.md, jury_rehearsal_verdict.json",
                endpoint_or_port="/api/release/clean-room/*, /api/demo/jury-rehearsal/*",
                update_rate="operator action",
                data_fields=["extract path", "endpoint smoke results", "release verdict", "competition blockers", "safety invariant"],
                safety_boundary="Clean-room and jury rehearsal interfaces never arm, enable hardware or issue physical commands.",
                failure_behavior="Missing clean-room or rehearsal evidence appears as warning/blocker in report UI.",
                verification_method="Phase 23/24 clean-room smoke, report export and UI evidence tests",
                ktr_description="Demo/evidence/release dogrulama arayuzudur; fiziksel komut uretmez. Competition readiness icin production YOLO, gercek kamera, Pico telemetry ve self-test gerekir.",
                export_evidence_path="release_portability_audit.md, cleanroom_smoke_results.json, jury_rehearsal_summary.md, jury_rehearsal_verdict.json",
            ),
            InterfaceRecord(
                interface_id="portable_launcher",
                name="Portable Launcher Interface",
                category="deployment_interface",
                direction="operator OS to backend/frontend",
                producer="start scripts",
                consumer="Python uv/FastAPI and browser",
                transport="Windows batch / Linux shell",
                protocol="process launch",
                message_format="launcher log text",
                endpoint_or_port="start_windows.bat, start_linux.sh, 127.0.0.1:8000",
                update_rate="startup",
                data_fields=["python version", "uv availability", "port status", "log path"],
                safety_boundary="Launcher starts software only; it does not enable physical hardware.",
                failure_behavior="Missing dependencies or busy port produce user-readable error.",
                verification_method="First-run and launcher file existence checks",
                ktr_description="ZIP taşınabilir kullanım için Windows/Linux başlatma arayüzleri.",
            ),
            InterfaceRecord(
                interface_id="electronic_signal_placeholder",
                name="Electronic Power/Signal Interface Definition",
                category="electronic_power_signal_interface_placeholder",
                direction="future Pico to motor/servo inputs",
                producer="Pico local safety firmware in future phase",
                consumer="TMC2209, servo, E-stop and limit inputs",
                transport="GPIO/UART/PWM planned",
                protocol="STEP/DIR/UART/PWM/input signals",
                message_format="electrical signals, currently disabled",
                endpoint_or_port="Pico 2 pin profile placeholder",
                update_rate="future hardware bring-up",
                data_fields=["STEP", "DIR", "UART", "PWM", "ESTOP", "LIMITS"],
                safety_boundary="No GPIO, STEP/DIR/PWM output is produced in this software phase.",
                failure_behavior="Physical command flags are rejected by config and runtime gates.",
                verification_method="Safety invariant tests",
                ktr_description="Sistem arayüz tanımı kapsamında planlanan fiziksel güç/sinyal hatlarıdır; mevcut yazılım release’inde fiziksel çıkış kapalıdır.",
            ),
        ]
