from typing import Protocol


class SerialTransport(Protocol):
    def open(self) -> None: ...

    def close(self) -> None: ...

    def readline(self) -> bytes: ...

    def write(self, data: bytes) -> int: ...

    @property
    def is_open(self) -> bool: ...
